ProyectoWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static  

urlpatterns = [
    path('admin/', admin.site.urls),
    path('servicios/', include('servicios.urls')),
    path('blog/', include('blog.urls')),
    path('contacto/', include('contacto.urls')),
    path('', include('ProyectoWebApp.urls')),
    path('tienda/', include('tienda.urls')),
    path('carro/', include('carro.urls')),
    path('autenticacion/', include('autenticacion.urls')),
    path('pedidos/', include('pedidos.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.blog, name="Blog"),
    #el int para que en la url tome como numero el id
    path('categoria/<int:categoria_id>', views.categoria, name="categoria"),
]

carro/urls.py
from django.urls import path
from . import views

#agregamos un namespace para que tenemos en otra aplicacion rutas con los mismos nombres evitamos una colision
app_name="carro"

urlpatterns = [
    path("agregar/<int:producto_id>/", views.agregar_producto, name="agregar"),
    path("eliminar/<int:producto_id>/", views.eliminar_producto, name="eliminar"),
    path("restar/<int:producto_id>/", views.restar_producto, name="restar"),
    path("limpiar/<int:producto_id>/", views.limpiar_carro, name="limpiar"),
]

carro/views.py
from django.shortcuts import render
from .carro import Carro
from tienda.models import Producto
from django.shortcuts import redirect

# Create your views here.

def agregar_producto(request, producto_id):
    

    carro = Carro(request)
    producto = Producto.objects.get(id=producto_id)

    carro.agregar(producto=producto)

    return redirect("Tienda")

def eliminar_producto(request, producto_id):

    carro = Carro(request)
    producto = Producto.objects.get(id=producto_id)

    carro.eliminar(producto=producto)

    return redirect("Tienda")

def restar_producto(request, producto_id):

    carro = Carro(request)
    producto = Producto.objects.get(id=producto_id)

    carro.restar_producto(producto=producto)

    return redirect("Tienda")

def limpiar_carro(request, producto_id):

    carro = Carro(request)
    carro.limpiar_carro()

    return redirect("Tienda")

tienda/templates/carro/widget.html
    <table class="table table-bordered" style="color: white; background-color: midnightblue; margin-left: 5%;">
    <thead>
        <tr>
           <th colspan="3" class="text-center">
                CARRO
           </th> 
        </tr>
        <tr>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Suma</th>
        </tr>
    </thead>

    <tbody>
        <!-- si hay elementos en el carro -->
        {% if request.session.carro.items %}
            {% for key, value in request.session.carro.items %}
                <tr class="text-center">
                    <td>{{value.nombre}}</td>
                    <td>{{value.cantidad}}</td>
                    <td>
                        <a href="{% url 'carro:agregar' value.producto_id %}" class="btn btn-sm btn-success">+</a>
                        <a href="{% url 'carro:restar' value.producto_id %}" class="btn btn-sm btn-success">-</a><br>
                        
                        {{value.precio}} €

                    </td>
                </tr>
            {% endfor %}
        <!-- si esta vacio, muestra un mensaje de advertencia -->
        {% else %}
            <tr>
                <td colspan="3">
                    <div class="alert alert-danger text-center">
                        Sin Productos
                    </div>
                </td>
            </tr>
        {% endif %}
    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">
                Total: {{importe_total_carro}} €
            </td>
        </tr>
        <!-- la opcion de hacer pedido solo será disponible si hay sesion activa y productos en el carro -->
        {% if request.session.carro.items %}
        <tr>
            <td colspan="3" style="text-align: center;">
                <a href="../pedidos" class="btn btn-success">Hacer pedido</a>
            </td>
        </tr>
        {% endif %}
    </tfoot>

</table>